package com.example.ui

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    // Global & Navigation
    val appName: String,
    val tabHome: String,
    val tabSaved: String,
    val tabShopping: String,
    val tabSettings: String,
    
    // Home / Fridge Scanner
    val takePhoto: String,
    val uploadPhoto: String,
    val analyzing: String,
    val detectedIngredients: String,
    val editIngredientsTip: String,
    val addIngredient: String,
    val findRecipes: String,
    
    // Filters
    val filters: String,
    val vegetarian: String,
    val vegan: String,
    val keto: String,
    val lowCarb: String,
    val highProtein: String,
    val glutenFree: String,
    val dairyFree: String,
    val halal: String,
    val healthyMeals: String,

    // Recipe generated lists
    val matchingRecipes: String,
    val sortBy: String,
    val match: String,
    val easy: String,
    val medium: String,
    val hard: String,

    // Recipe Detail
    val ingredients: String,
    val missing: String,
    val nutrition: String,
    val instructions: String,
    val addToShoppingList: String,
    val startCooking: String,
    
    // Nutrition breakdown
    val calories: String,
    val protein: String,
    val carbs: String,
    val fat: String,
    val fiber: String,
    
    // Cooking Mode
    val step: String,
    val next: String,
    val previous: String,
    val finish: String,
    val playTts: String,
    val pauseTts: String,

    // Shopping List
    val manualAddHint: String,
    val add: String,
    val clearCompleted: String,
    val emptyList: String,

    // Settings
    val settings: String,
    val language: String,
    val darkMode: String,
    val ttsEnabled: String,
    val notifications: String,
    val aboutApp: String,
    val version: String,
    val devInfo: String,
    val privacyInfo: String,
    
    // Misc
    val save: String,
    val error: String,
    val retry: String
)

val EnglishStrings = AppStrings(
    appName = "Smart Fridge & Culinary Assistant",
    tabHome = "Scanner",
    tabSaved = "Saved",
    tabShopping = "Shopping",
    tabSettings = "Settings",
    takePhoto = "Take Photo",
    uploadPhoto = "Upload Photo",
    analyzing = "Analyzing contents...",
    detectedIngredients = "Detected Ingredients",
    editIngredientsTip = "You can manually add, remove, or correct ingredients.",
    addIngredient = "Add Ingredient",
    findRecipes = "Find Recipes",
    filters = "Dietary Filters",
    vegetarian = "Vegetarian",
    vegan = "Vegan",
    keto = "Keto",
    lowCarb = "Low Carb",
    highProtein = "High Protein",
    glutenFree = "Gluten Free",
    dairyFree = "Dairy Free",
    halal = "Halal",
    healthyMeals = "Healthy Meals",
    matchingRecipes = "Matching Recipes",
    sortBy = "Sort By",
    match = "Match",
    easy = "Easy",
    medium = "Medium",
    hard = "Hard",
    ingredients = "Ingredients",
    missing = "Missing",
    nutrition = "Nutrition Info",
    instructions = "Instructions",
    addToShoppingList = "Add to Shopping List",
    startCooking = "Start Cooking",
    calories = "Calories",
    protein = "Protein",
    carbs = "Carbs",
    fat = "Fat",
    fiber = "Fiber",
    step = "Step",
    next = "Next",
    previous = "Previous",
    finish = "Finish",
    playTts = "Play Voice",
    pauseTts = "Pause Voice",
    manualAddHint = "Add item manually...",
    add = "Add",
    clearCompleted = "Clear Completed",
    emptyList = "Your shopping list is empty.",
    settings = "Settings",
    language = "Language",
    darkMode = "Dark Mode",
    ttsEnabled = "Text-to-Speech",
    notifications = "Notifications",
    aboutApp = "About App",
    version = "Version",
    devInfo = "Developed safely and responsibly.",
    privacyInfo = "Privacy: Your fridge photos are only analyzed securely, no data is sold.",
    save = "Save",
    error = "Error occurred",
    retry = "Retry"
)

val SomaliStrings = AppStrings(
    appName = "Talaajadda Casriga & Kaaliyaha Cuntada",
    tabHome = "Sawirka",
    tabSaved = "Kaydin",
    tabShopping = "Iibsasho",
    tabSettings = "Gidaaminta",
    takePhoto = "Sawir qaad",
    uploadPhoto = "Soo geli Sawir",
    analyzing = "Waa la falanqaynayaa...",
    detectedIngredients = "Waxyaabaha La Helay",
    editIngredientsTip = "Wad ku dari kartaa, tirtiri kartaa ama saxi kartaa agabka.",
    addIngredient = "Kudar Agab",
    findRecipes = "Raadi Cuntooyin",
    filters = "Shaandhada Cuntada",
    vegetarian = "Qudaar Kaliya",
    vegan = "Xoolo La'aan (Vegan)",
    keto = "Keto",
    lowCarb = "Karbohaydrayt-Hoose",
    highProtein = "Burotiinka-Sare",
    glutenFree = "Gluten La'aan",
    dairyFree = "Caanaha La'aan",
    halal = "Xalaal",
    healthyMeals = "Cunto Caafimaad",
    matchingRecipes = "Cuntooyinka Kula Taliyey",
    sortBy = "Ku kala horaysii",
    match = "Isu-ekaansho",
    easy = "Fudud",
    medium = "Dhexdhexaad",
    hard = "Adag",
    ingredients = "Agabka Cuntada",
    missing = "Ka Maqan",
    nutrition = "Nafaqada",
    instructions = "Habka loo kariyo",
    addToShoppingList = "Kudar Liiska Iibsiga",
    startCooking = "Bilaab Karinta",
    calories = "Kalooriska",
    protein = "Burotiin",
    carbs = "Karbohaydrayt",
    fat = "Dufan",
    fiber = "Fayber",
    step = "Tallaabada",
    next = "Xiga",
    previous = "Hore",
    finish = "Dhammee",
    playTts = "Daar Codka",
    pauseTts = "Haki Codka",
    manualAddHint = "Gacantaada kudar agab...",
    add = "Kudar",
    clearCompleted = "Tirtir Dhamaadka",
    emptyList = "Liiska iibsigaagu wuu madhan yahay.",
    settings = "Gidaaminta",
    language = "Luqadda",
    darkMode = "Muuqaalka Madow",
    ttsEnabled = "Qoraalka-Madow-Isu-beddelka-Cod",
    notifications = "Ogeysiisyada",
    aboutApp = "Ku Saabsan Barnaamijka",
    version = "Nooc",
    devInfo = "Si aamin ah ayaa loo horumariyey.",
    privacyInfo = "Qarsoodi: Sawirrada talaajadda si sugan ayaa loo falanqeeyaa, xogta lama iibiyo.",
    save = "Kaydi",
    error = "Cillad ayaa dhacday",
    retry = "Ku noqo"
)

val LocalStrings = staticCompositionLocalOf { EnglishStrings }
